version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: 7mgkO
      POSTGRES_DB: quality_audit
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data